spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dictionary-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

feign:
  iam-service:
    url: https://iam-service-210633814475.us-central1.run.app/api

security:
  internal-request:
    secret: ${INTERNAL_SECRET}
