openapi: 3.0.0
info:
  title: Dictionary service API Spec for TKD
  description: Endpoints for dictionary related functions
  version: 1.0.0

servers:
  - url: http://localhost:8082
    description: Local development server

paths:
  /dict/add:
    post:
      tags:
        - DictV1
      operationId: addToDictionary
      summary: Add a new word or phrase to the dictionary
      requestBody:
        description: The submitted word or phrase details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WordRequest"
      responses:
        "200":
          description: Contribution feedback
          content:
            application/json:
              schema:
                type: number
  /dict/random:
    get:
      tags:
        - DictV1
      operationId: getRandomWords
      summary: Get a set of random words to display
      responses:
        "200":
          description: The set of random words retrieved wrapped in a Page object
          content:
            application/json:
              schema:
                type: object
  /dict/{wordId}:
    get:
      tags:
        - DictV1
      operationId: findWord
      summary: Find word based on passed wordId
      parameters:
        - in: path
          name: wordId
          required: true
          description: ID of word to be searched
          schema:
            type: number
      responses:
        "200":
          description: Word view model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictionaryItem'

components:
  schemas:
    WordRequest:
      type: object
      properties:
        word:
          type: string
        translations:
          type: array
          items:
            $ref: '#/components/schemas/TranslationRequest'
        usageExamples:
          type: array
          items:
            $ref: '#/components/schemas/UsageExampleRequest'
    TranslationRequest:
      type: object
      properties:
        translation:
          type: string
    UsageExampleRequest:
      type: object
      properties:
        example:
          type: string
        exampleTranslation:
          type: string
    DictionaryItem:
      type: object
      properties:
        word:
          type: string
        translations:
          type: string
        usageExamples:
          type: string
