spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: iam-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8081
  servlet:
    context-path: /api

security:
  internal-request:
    secret: ${INTERNAL_SECRET}
