openapi: 3.0.0
info:
  title: API Spec for TKD
  description: API Endpoint descriptions for TKD
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Local development server

paths:
  /auth/register:
    post:
      tags:
        - IamV1
      operationId: registerUser
      summary: Register user into database and return token
      parameters:
        - in: header
          name: X-XSRF-TOKEN
          schema:
            type: string
          required: true
          description: csrf token
      requestBody:
        description: The user information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
      responses:
        "200":
          description: Registration feedback message
          content:
            application/json:
              schema:
                type: string
  /auth/login:
    post:
      tags:
        - IamV1
      operationId: loginUser
      summary: Authenticate and authorize user. Return tokens.
      parameters:
        - in: header
          name: X-XSRF-TOKEN
          schema:
            type: string
          required: true
          description: csrf token
      requestBody:
        description: Login information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: The token and response messages
          content:
            application/json:
              schema:
                type: string
  /auth/logout:
    post:
      tags:
        - IamV1
      operationId: logoutUser
      summary: Logout user.
      parameters:
        - in: header
          name: X-XSRF-TOKEN
          schema:
            type: string
          required: true
          description: csrf token
      responses:
        "200":
          description: Response message after logout
          content:
            application/json:
              schema:
                type: string
  /auth/refresh:
    post:
      tags:
        - IamV1
      operationId: refreshToken
      summary: Refresh JWT token based on refresh token
      responses:
        "200":
          description: The new JWT token and username of the current user
          content:
            application/json:
              schema:
                type: string
  /auth/check-username:
    get:
      tags:
        - IamV1
      operationId: checkUsernameAvailable
      summary: Check whether username is already in use.
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: The username to be checked
      responses:
        "200":
          description: Just return a boolean whether it's already in use or not
          content:
            application/json:
              schema:
                type: boolean
  /auth/check-email:
    get:
      tags:
        - IamV1
      operationId: checkEmailAvailable
      summary: Check whether email is already registered.
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: true
          description: The email to be checked
      responses:
        "200":
          description: Just return a boolean whether it's already registered or not
          content:
            application/json:
              schema:
                type: boolean
  /user/details:
    get:
      tags:
        - IamV1
      operationId: getUserDetails
      summary: Get the details of the logged in user
      parameters:
        - in: query
          name: includeId
          schema:
            type: boolean
          required: true
          description: specifies whether the ID of the user should be returned
      responses:
        "200":
          description: Object holding details of the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserView"
  /internal/user/details:
    get:
      tags:
        - IamV1
      operationId: getIamUserDetails
      summary: Get the details of IamUser for authentication only
      parameters:
        - in: header
          name: X-internal-call
          schema:
            type: string
          required: true
        - in: query
          name: loginId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Object holding basic details of IamUser
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IamUserData"
  /admin/check:
    get:
      tags:
        - IamV1
      operationId: adminCheck
      summary: Check if user is ADMIN
      responses:
        "200":
          description: boolean to indicate whether user is admin
          content:
            application/json:
              schema:
                type: boolean
  /auth/csrf:
    get:
      tags:
        - IamV1
      operationId: issueCsrfToken
      summary: Issue a csrfToken
      responses:
        "200":
          description: issue a cookie for csrf token
  /auth/verify:
    get:
      tags:
        - IamV1
      operationId: checkIsUserAuthenticated
      summary: Check if the user is authenticated based on their access token
      responses:
        "200":
          description: send a boolean to check if the user is already logged in
          content:
            application/json:
              schema:
                type: boolean
  /user/{userId}:
    get:
      tags:
        - IamV1
      operationId: getUser
      summary: get user based on user ID
      parameters:
        - in: path
          name: userId
          schema:
            type: number
          required: true
          description: user ID to use in search
      responses:
        "200":
          description: details of the found user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserView"

components:
  schemas:
    RegistrationRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    UserView:
      type: object
      properties:
        id:
          type: number
        username:
          type: string
    IamUserData:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string